// Get Properties
export const GET_ALL_PROPERTIES_REQUEST = "GET_ALL_PROPERTIES_REQUEST";
export const GET_ALL_PROPERTIES_SUCCESS = "GET_ALL_PROPERTIES_SUCCESS";
export const GET_ALL_PROPERTIES_FAILURE = "GET_ALL_PROPERTIES_FAILURE";

// Get Properties based on Id
export const GET_ALL_PROPERTIES_DETAILS_REQUEST =
  "GET_ALL_PROPERTIES_DETAILS_REQUEST";
export const GET_ALL_PROPERTIES_DETAILS_SUCCESS =
  "GET_ALL_PROPERTIES_DETAILS_SUCCESS";
export const GET_ALL_PROPERTIES_DETAILS_FAILURE =
  "GET_ALL_PROPERTIES_DETAILS_FAILURE";

// Post News Letter Email
export const POST_NEWS_LETTER_REQUEST = "POST_NEWS_LETTER_REQUEST";
export const POST_NEWS_LETTER_SUCCESS = "POST_NEWS_LETTER_SUCCESS";
export const POST_NEWS_LETTER_FAILURE = "POST_NEWS_LETTER_FAILURE";

// Post Contact Us
export const POST_CONTACT_US_REQUEST = "POST_CONTACT_US_REQUEST";
export const POST_CONTACT_US_SUCCESS = "POST_CONTACT_US_SUCCESS";
export const POST_CONTACT_US_FAILURE = "POST_CONTACT_US_FAILURE";

// Get All Blogs
export const GET_ALL_BLOGS_REQUEST = "GET_ALL_BLOGS_REQUEST";
export const GET_ALL_BLOGS_SUCCESS = "GET_ALL_BLOGS_SUCCESS";
export const GET_ALL_BLOGS_FAILURE = "GET_ALL_BLOGS_FAILURE";

// Get Blogs based on Id
export const GET_ALL_BLOGS_DETAILS_REQUEST =
  "GET_ALL_PROPERTIES_DETAILS_REQUEST";
export const GET_ALL_BLOGS_DETAILS_SUCCESS =
  "GET_ALL_PROPERTIES_DETAILS_SUCCESS";
export const GET_ALL_BLOGS_DETAILS_FAILURE =
  "GET_ALL_PROPERTIES_DETAILS_FAILURE";
