export const properties = [
  {
    id: "1",
    image:
      "https://all-sites-under.s3.us-east-2.amazonaws.com/REMP196/LIVE/uploads/property/261/image/low/1718106090.jpg",
    name: "Luxurious Boutique Retreat",
    location: "Noida-Greater Noida Expy, Noida, UP , India",
    builtupArea: "5000",
    listedby: "owner",
    assetType: "Residential",
    properyType: "condo",
    TotalNoOfUnit: "40",
    startingBid: "600,00,000",
    lotSize: "1.50",
    propertBuiltYear: "2015",
    interiorAccess: "No",
    acceptsBuyersTitle: "No",
    categories: "Residential",
  },
  {
    id: "2",
    image:
      "https://all-sites-under.s3.us-east-2.amazonaws.com/REMP196/LIVE/uploads/property/255/image/low/1718086572.jpg",
    name: "Transport Hub",
    location: "TX-1604 Loop, San Antonio, TX , United States ",
    builtupArea: "5000",
    listedby: "owner",
    assetType: "Residential",
    properyType: "condo",
    TotalNoOfUnit: "40",
    startingBid: "600,00,000",
    lotSize: "1.50",
    propertBuiltYear: "2015",
    interiorAccess: "No",
    acceptsBuyersTitle: "No",
    categories: "Residential",
  },
  {
    id: "3",
    image:
      "https://all-sites-under.s3.us-east-2.amazonaws.com/REMP196/LIVE/uploads/property/291/image/low/1718190611.png",
    name: "Parkway Gas Station",
    location: "USA Pkwy, sparks, NV , United States.",
    builtupArea: "5000",
    listedby: "owner",
    assetType: "Residential",
    properyType: "condo",
    TotalNoOfUnit: "40",
    startingBid: "600,00,000",
    lotSize: "1.50",
    propertBuiltYear: "2015",
    interiorAccess: "No",
    acceptsBuyersTitle: "No",
    categories: "Residential",
  },
  {
    id: "4",
    image:
      "https://all-sites-under.s3.us-east-2.amazonaws.com/REMP196/LIVE/uploads/property/238/image/low/1711995688.jpg",
    name: "Refreshing Rustic Retreats",
    location: "2150 Town Square Pl, SugarLand, TX, US.",
    builtupArea: "5000",
    ownership: "soleownership",
    listedby: "owner",
    assetType: "Residential",
    properyType: "condo",
    TotalNoOfUnit: "40",
    startingBid: "600,00,000",
    lotSize: "1.50",
    propertBuiltYear: "2015",
    interiorAccess: "No",
    acceptsBuyersTitle: "No",
    categories: "Residential",
  },
  {
    id: "5",
    image:
      "https://all-sites-under.s3.us-east-2.amazonaws.com/REMP196/LIVE/uploads/property/260/image/low/1718105788.jpg",
    name: "Prime Industrial Land",
    location: "Uttarahalli Main Rd, Bengaluru, KA , India.",
    builtupArea: "5000",
    listedby: "owner",
    assetType: "Residential",
    properyType: "condo",
    TotalNoOfUnit: "40",
    startingBid: "600,00,000",
    lotSize: "1.50",
    propertBuiltYear: "2015",
    interiorAccess: "No",
    acceptsBuyersTitle: "No",
    categories: "Hotel",
  },
  {
    id: "6",
    image:
      "https://all-sites-under.s3.us-east-2.amazonaws.com/REMP196/LIVE/uploads/property/257/image/low/1718262765.jpg",
    name: "Farming Haven",
    location: "Indira Gandhi Int'l T3 Rd, DL, India",
    builtupArea: "5000",
    listedby: "owner",
    assetType: "Residential",
    properyType: "condo",
    TotalNoOfUnit: "40",
    startingBid: "600,00,000",
    lotSize: "1.50",
    propertBuiltYear: "2015",
    interiorAccess: "No",
    acceptsBuyersTitle: "No",
    categories: "Hotel",
  },
  {
    id: "7",
    image:
      "https://all-sites-under.s3.us-east-2.amazonaws.com/REMP196/LIVE/uploads/property/258/image/low/1718105468.jpg",
    name: "Premier Commercial Space",
    location: "Mumbai - Pune Expy, Navi Mumbai, MH , India.",
    builtupArea: "5000",
    listedby: "owner",
    assetType: "Residential",
    properyType: "condo",
    TotalNoOfUnit: "40",
    startingBid: "600,00,000",
    lotSize: "1.50",
    propertBuiltYear: "2015",
    interiorAccess: "No",
    acceptsBuyersTitle: "No",
    categories: "Hotel",
  },
  {
    id: "8",
    image:
      "https://all-sites-under.s3.us-east-2.amazonaws.com/REMP196/LIVE/uploads/property/256/image/low/1718104432.jpg",
    name: "Exquisite Estate",
    location: "Kochi - Salem Hwy, Ernakulam, KL , India",
    builtupArea: "5000",
    listedby: "owner",
    assetType: "Residential",
    properyType: "condo",
    TotalNoOfUnit: "40",
    startingBid: "600,00,000",
    lotSize: "1.50",
    propertBuiltYear: "2015",
    interiorAccess: "No",
    acceptsBuyersTitle: "No",
    categories: "Hotel",
  },
  {
    id: "9",
    image:
      "https://all-sites-under.s3.us-east-2.amazonaws.com/REMP196/LIVE/uploads/property/280/image/low/1718134947.jpg",
    name: "My Land",
    location: "15875 FM 529, Houston, TX, United States",
    builtupArea: "5000",
    listedby: "owner",
    assetType: "Residential",
    properyType: "condo",
    TotalNoOfUnit: "40",
    startingBid: "600,00,000",
    lotSize: "1.50",
    propertBuiltYear: "2015",
    interiorAccess: "No",
    acceptsBuyersTitle: "No",
    categories: "Apartment",
  },
  {
    id: "10",
    image:
      "https://all-sites-under.s3.us-east-2.amazonaws.com/REMP196/LIVE/uploads/property/281/image/low/1718135635.jpg",
    name: "My Plaza",
    location: "Florida A1A, Miami, FL 33125, United States  ",
    builtupArea: "5000",
    listedby: "owner",
    assetType: "Residential",
    properyType: "condo",
    TotalNoOfUnit: "40",
    startingBid: "600,00,000",
    lotSize: "1.50",
    propertBuiltYear: "2015",
    interiorAccess: "No",
    acceptsBuyersTitle: "No",
    categories: "Apartment",
  },
  {
    id: "11",
    image:
      "https://all-sites-under.s3.us-east-2.amazonaws.com/REMP196/LIVE/uploads/property/283/image/low/1718137884.webp",
    name: "Sunshine Villa",
    location: "2150 Town Square Place, Sugar Land, TX, US",
    builtupArea: "5000",
    listedby: "owner",
    assetType: "Residential",
    properyType: "condo",
    TotalNoOfUnit: "40",
    startingBid: "600,00,000",
    lotSize: "1.50",
    propertBuiltYear: "2015",
    interiorAccess: "No",
    acceptsBuyersTitle: "No",
    categories: "Apartment",
  },
  {
    id: "12",
    image:
      "https://all-sites-under.s3.us-east-2.amazonaws.com/REMP196/LIVE/uploads/property/284/image/low/1718139132.jpg",
    name: "House",
    location: "3737Branford Pl, SugarLand, TX, US",
    builtupArea: "5000",
    listedby: "owner",
    assetType: "Residential",
    properyType: "condo",
    TotalNoOfUnit: "40",
    startingBid: "600,00,000",
    lotSize: "1.50",
    propertBuiltYear: "2015",
    interiorAccess: "No",
    acceptsBuyersTitle: "No",
    categories: "Apartment",
  },
];
